# dataset
dataset: DistillRecDial
tokenize:
  rec: bert
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 7
scale: 1
# model
rec_model: SASREC
hidden_dropout_prob: 0.3
initializer_range: 0.05
hidden_size: 128
max_history_items: 7
num_attention_heads: 1
attention_probs_dropout_prob: 0.3
hidden_act: gelu
num_hidden_layers: 2
# optim
rec:
  epoch: 50
  batch_size: 64
  optimizer:
    name: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 0.0000
  lr_bert: !!float 1e-3
  early_stop: true
  impatience: 5
  stop_mode: min
