# dataset
dataset: DistillRecDial
tokenize:
  rec: bert
  conv: gpt2
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 7
scale: 1
# model
# rec
rec_model: InspiredRec
# conv
conv_model: InspiredConv
# embedding: word2vec
embedding_dim: 300
use_dropout: False
dropout: 0.3
decoder_hidden_size: 256
decoder_num_layers: 1
# optim
rec:
  epoch: 0 #30
  batch_size: 64
  optimizer:
    name: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 0.0000
  early_stop: False
  stop_mode: min
  impatience: 10
  lr_bert: !!float 1e-4
conv:
  epoch: 30
  batch_size: 8
  optimizer:
    name: AdamW
    lr: !!float 3e-5
    eps: !!float 1e-06
    weight_decay: !!float 0.01
  lr_scheduler:
    name: TransformersLinearLR
    warmup_steps: 100
  early_stop: true
  impatience: 3
  stop_mode: min
